import { Type, Transform } from 'class-transformer'
import {
  IsOptional,
  IsString,
  Matches,
  MaxLength,
  ValidateIf,
  ValidateNested,
} from 'class-validator'
import { ApiPropertyOptional } from '@nestjs/swagger'

const trimString = ({ value }: { value: unknown }): unknown =>
  typeof value === 'string' ? value.trim() : value

class UserAddressLocationDto {
  @ApiPropertyOptional({ example: 'Ben Nghe' })
  @IsOptional()
  @Transform(trimString)
  @IsString()
  @MaxLength(120)
  ward?: string

  @ApiPropertyOptional({ example: 'District 1' })
  @IsOptional()
  @Transform(trimString)
  @IsString()
  @MaxLength(120)
  district?: string

  @ApiPropertyOptional({ example: 'Ho Chi Minh City' })
  @IsOptional()
  @Transform(trimString)
  @IsString()
  @MaxLength(120)
  city?: string
}

class UserAddressDto {
  @ApiPropertyOptional({ example: 'Nguyen Van A' })
  @IsOptional()
  @Transform(trimString)
  @IsString()
  @MaxLength(120)
  recipientName?: string

  @ApiPropertyOptional({ example: '+84901234567' })
  @IsOptional()
  @Transform(trimString)
  @IsString()
  @MaxLength(40)
  phone?: string

  @ApiPropertyOptional({ example: '123 Le Loi' })
  @IsOptional()
  @Transform(trimString)
  @IsString()
  @MaxLength(240)
  line1?: string

  @ApiPropertyOptional({ type: UserAddressLocationDto })
  @IsOptional()
  @ValidateNested()
  @Type(() => UserAddressLocationDto)
  location?: UserAddressLocationDto

  @ApiPropertyOptional({ example: 'Call before delivery' })
  @IsOptional()
  @Transform(trimString)
  @IsString()
  @MaxLength(500)
  notes?: string
}

export class UpdateUserProfileDto {
  @ApiPropertyOptional({ example: 'Nguyen Van A' })
  @IsOptional()
  @Transform(trimString)
  @IsString()
  @MaxLength(120)
  name?: string

  @ApiPropertyOptional({
    example: 'users/0f3e/avatar/a1f2-avatar.webp',
    nullable: true,
    description: 'Set to null to remove the current avatar.',
  })
  @ValidateIf((_, value) => value !== undefined && value !== null)
  @Transform(trimString)
  @IsString()
  @MaxLength(1024)
  @Matches(/^users\/[^/]+\/avatar\/[^/]+$/, {
    message: 'avatarKey must be an avatar key generated by /upload/presign.',
  })
  avatarKey?: string | null

  @ApiPropertyOptional({ type: UserAddressDto })
  @IsOptional()
  @ValidateNested()
  @Type(() => UserAddressDto)
  address?: UserAddressDto
}
